url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
sass:
  sass_dir: assets/css 

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

tagline: "An awesome tagline"
email: your.email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Add description here
author: name
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card